version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - 5432:5432
    container_name: pgsql
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser    
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: helpsi

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8100:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"
    networks:
      - pg-network 
    depends_on:
      - pgsql

networks:
  pg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16

